### ISSUE TITLE
Wrong output on Chapter 5: Problem 1 (CountDiv) Problem

### ISSUE THREAD

**Issue by saanpritom** [Dineshkarthik/codility_training#2]
Test cases are not matched for the solution of the problem (Chapter 5: Problem 1 [CountDiv]). The solution function is returning a float number but integer is expected. If math.floor function is used with proper 0 logic then it is failing in some test cases.

**Comment by Dineshkarthik** [comment]
@saanpritom thanks for pointing this out, **I realized that this repo is outdated need to re-check all the solutions.**
When I created this repo the python version supported by codility was python2. Now the python version in codility is 3.6 so the breaking changes are introduced.

The earlier code worked when I submitted my solution 4 years ago and even now I tried running it on Python2 and it works and returns an integer.

**Comment by Dineshkarthik** [comment]
Updated all my code to 3.6 in PR #4

**Comment by saanpritom** [comment]
Hi, @Dineshkarthik thank you for the update.
